# 이니셜 로컬 yml
spring:
  config:
    import: optional:application-base.yml

  # db setting
  datasource:
    url: jdbc:mysql://192.168.219.171:3306/initial
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: miroit#0621^^

  # jpa setting
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false  # p6spy가 대신 로그를 출력하므로 false로 설정

# query logging setting
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariDataSource: DEBUG
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

# swagger setting
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha # 알파벳 순서로 정렬
    operations-sorter: method # 메소드 순서로 정렬
    doc-expansion: none # 카테고리가 접힌상태로 로딩
  packages-to-scan: com.miroit
  title: Initial API 문서 (local)
  version: 1.0

# jwt setting
jwt:
  issuer: initial-api
  access-token-secret-key: initial-api-access-secret_initial-api-access-secret
  access-token-expiration: 3600000 # 1개월
  refresh-token-secret-key: initial-api-refresh-secret_initial-api-refresh-secret
  refresh-token-expiration: 2592000000 # 1개월

# file
file:
  upload:
    root-path: tmp/files/uploads
    file-max-size: 10485760 # 10MB (10 * 1024 * 1024)

# internal-api setting
internal-api:
  visit:
    url: http://visit-api.miroit.kro.kr
  content:
    url: http://content-api.miroit.kro.kr
  notification:
    url: http://notification-api.miroit.kro.kr
  approval:
    url: http://approval-api.miroit.kro.kr
  access:
    url: http://access-api.miroit.kro.kr
  auth:
    url: http://auth-api.miroit.kro.kr
  member:
    url: http://member-api.miroit.kro.kr
  parking:
    url: http://parking-api.miroit.kro.kr
