# 공통 yml
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # paging default setting
  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort

# health
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always