# 공통 dev yml

# feign URL list
feign:
  initial-api:
    url: initial-api:9090
  visit-api:
    url: visit-api:9091
  content-api:
    url: content-api:9092
  notification-api:
    url: notification-api:9093
  approval-api:
    url: approval-api:9094
