# jwt setting
jwt:
  issuer: approval-api
  access-token-secret-key: approval-api-access-secret_approval-api-access-secret
  access-token-expiration: 3600000 # 1개월
  refresh-token-secret-key: approval-api-refresh-secret_approval-api-refresh-secret
  refresh-token-expiration: 2592000000 # 1개월

jasypt:
  encryptor:
    password: miroit

springdoc:
  title: gateway
  version: 1.0.0

spring:
  # db setting
  datasource:
    url: jdbc:mysql://192.168.219.171:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: miroit#0621^^
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        namespaces: ["miroit-access"]
        service-labels:
          gateway-access: "true"
    gateway:
      server:
        webflux:
          routes:
            - id: visit
              uri: lb://visit-api
              predicates:
                - Path=/visit/**
              filters:
                - StripPrefix=1

            - id: notification
              uri: lb://notification-api
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1

            - id: approval
              uri: lb://approval-api
              predicates:
                - Path=/approval/**
              filters:
                - StripPrefix=1

            - id: content
              uri: lb://content-api
              predicates:
                - Path=/content/**
              filters:
                - StripPrefix=1


# health
management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health, prometheus
  info:
    env:
      enabled: true
logging:
  level:
    com.miroit.gateway.global.filter.RequestLoggingFilter: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.kubernetes: INFO