miroit:
  service:
    schema: visit
    title: Visit

spring:
  config:
    import: optional:application-base-local.yml

# feign URL list
feign:
  initial-api:
    url: localhost:9090
  visit-api:
    url: localhost:9091
  content-api:
    url: localhost:9092
  notification-api:
    url: localhost:9093
  approval-api:
    url: localhost:9094