# 콘텐츠 개발 yml
spring:
  config:
    import: optional:application-base.yml

  # db setting
  datasource:
    url: ENC(9vDSWtgW5LixCo17f4/EpO0GLX3cO5DcBVxx0c2MGHZViZ1GCkKDYSxwX9a361lAEVtBuGmW3HU=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(RK7w+W03ss/4JjxaJ5Wxuw==)
    password: ENC(N+Q3AoarzhldSB3OC1pCNVTvxUO0yE/I)

  # jpa setting
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false  # p6spy가 대신 로그를 출력하므로 false로 설정

# query logging setting
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariDataSource: DEBUG
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

# swagger setting
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha # 알파벳 순서로 정렬
    operations-sorter: method # 메소드 순서로 정렬
    doc-expansion: none # 카테고리가 접힌상태로 로딩
  packages-to-scan: com.miroit
  title: Content API 문서 (dev)
  version: 1.0

# file
file:
  upload:
    root-path: tmp/files/uploads
    file-max-size: 10485760 # 10MB (10 * 1024 * 1024)

# feign URL list
feign:
  initial-api:
    url: initial-api:9090
  visit-api:
    url: visit-api:9091
  content-api:
    url: content-api:9092
  notification-api:
    url: notification-api:9093
  approval-api:
    url: approval-api:9094